[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
auto_detect_solc = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@forge-std/=lib/forge-std/src/",
    "@stablecoin/../=../../stablecoin/"
]

[rpc_endpoints]
anvil = "http://localhost:8545"

[etherscan]
anvil = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "short"
multiline_func_header = "all"

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

